### ISSUE TITLE
how to apply Max width and height

### ISSUE THREAD

**Issue by OmerObaid** [Wondermarin/react-color-palette#19]
How can i apply max width and max height?
i tried to apply through css like this to the rcp class
```
.rcp {
    width: 100% !important;
    height: 100% !important; 
    border-radius: 0 !important;
}.
```
when i apply above css, i start getting hex values with dashes (#d5-40-40).

**Comment by Wondermarin** [comment]
Hi, thank you for your issue!

This is because the color that you get in the output depends on the size of the color picker area that you are trying to change in CSS. For these purposes, the `ColorPicker` component has `width` and `height` properties.

To display the component in full screen, you will need to pass `document.documentElement.clientWidth` to the `width` property and `document.documentElement.clientHeight` to the `height` property.

**Comment by OmerObaid** [comment]
Hello @Wondermarin thanks for the response.
I actually don't want it to be full size of the client, i want it to be full size of the parent div. I guess i should use use the useRef hook for that, am i right?

**Comment by Wondermarin** [comment]
> Hello @Wondermarin thanks for the response.
> I actually don't want it to be full size of the client, i want it to be full size of the parent div. I guess i should use use the useRef hook for that, am i right?

Yep

**Comment by OmerObaid** [comment]
@Wondermarin Thanks for the help Appreciated.
